name: travelapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  material_color_utilities: ^0.11.1
  vm_service: 14.3.1
  http: ^1.1.0 # HTTP library untuk API request
  provider: ^6.1.4 # State management library
  google_maps_flutter: ^2.5.0
  flutter_map: 8.1.1
  google_fonts: ^4.0.3
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gambar_bromo.jpeg
    - assets/images/gunung_sindoro.jpeg
    - assets/images/anyer.jpg
    - assets/images/jemur.jpg
    - assets/images/Snorkling_Pangandaran.jpg
    - assets/images/jetski.jpg
    - assets/images/MendakiBromo.jpg
    - assets/images/kawahIjen.webp
    - assets/images/mobil-offroad.jpg
    - assets/images/bus.jpg
    - assets/images/PANGANDARAN.webp

  # Deklarasi folder gambar untuk diakses dalam aplikasi
